// Bundle the frontend with Bun.build and inline it into one HTML page.
// The result is written as a TS module (src/page.gen.ts) that the server
// imports, so the page ships inside the server bundle: one request, no
// static-file plumbing.
//
//   bun build.ts          build once
//   bun build.ts --dev    rebuild on change and run the server with --watch
import { watch } from "node:fs";

const root = import.meta.dir;

async function bundle(entry: string): Promise<string> {
  const out = await Bun.build({ entrypoints: [`${root}/${entry}`], minify: true, target: "browser" });
  if (!out.success) throw new AggregateError(out.logs, `Failed to bundle ${entry}`);
  return out.outputs[0]!.text();
}

async function build() {
  const t0 = performance.now();
  const [js, css, template] = await Promise.all([
    bundle("src/client/main.ts"),
    bundle("src/client/styles.css"),
    Bun.file(`${root}/src/client/index.html`).text(),
  ]);
  const html = template
    .replace("/*css*/", () => css.trim())
    .replace("/*js*/", () => js.trim().replace(/<\/script/gi, "<\\/script"));

  await Bun.write(
    `${root}/src/page.gen.ts`,
    `// Generated by build.ts — do not edit.\nexport const PAGE = ${JSON.stringify(html)};\n`,
  );
  const kb = (n: number) => `${(n / 1024).toFixed(1)} KB`;
  const gz = Bun.gzipSync(html).length;
  console.log(`page: ${kb(html.length)} (${kb(gz)} gzipped) in ${(performance.now() - t0).toFixed(0)} ms`);
}

await build();

if (process.argv.includes("--dev")) {
  let timer: Timer | undefined;
  watch(`${root}/src`, { recursive: true }, (_, file) => {
    if (!file || file.endsWith("page.gen.ts")) return;
    clearTimeout(timer);
    timer = setTimeout(() => build().catch((e) => console.error(e)), 50);
  });
  Bun.spawn(["bun", "--watch", "server.ts"], { cwd: root, stdio: ["inherit", "inherit", "inherit"] });
}
